name: test
on: [push]
jobs:
   
  build:
    runs-on: self-hosted
    steps:

      # Runs a single command using the runners shell
      - name: Copy change-build to change-build 2
        run: |
           sshpass -p itrinegy sftp -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no itrinegy@192.168.202.182
           put /home/itrinegy/Development/Emulator-Build/change-build.sh .
