name: test
on: [push]
jobs:
   
  build:
    runs-on: self-hosted
    steps:

      # Runs a single command using the runners shell
      - name: Copy change-build to change-build 2
        run: |
            cd /home/itrinegy/Development/Emulator-Build
            ./deploy-change-build.sh
