name: deploy change build script
on: [push]
jobs:
   
  build:
    runs-on: self-hosted
    steps:

      - name: Push change build to machines
        run: |
            cd /home/itrinegy/Development/Emulator-Build
            ./deploy-change-build.sh
