name: test
on: [push]
jobs:
   
  build:
    runs-on: self-hosted
    steps:

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
